### ISSUE TITLE
Aircraft doesn't appear in aircraft  list

### ISSUE THREAD

**Issue by Pigensworth** [racerretrocoder/Flightgear-F-22A-Raptor#13]
For some reason with the newest update the aircraft simply won't appear in the list of aircrafts. I went back to when the Models file was updated on the 29th and it works fine, but the update after that (latest as of writing this) doesn't work. It could also be user error on my part, but I installed it the same way that I did the older versions that worked, so I'm guessing it's not. Any help would be appreciated!

**Comment by racerretrocoder** [comment]
@Pigensworth Try it now, It should hopefully work

**Comment by Pigensworth** [comment]
@racerretrocoder It still doesn't show up. I'm running FGFS version 2020.3.19 if that would make a difference.

**Comment by racerretrocoder** [comment]
Fixxed it, try it now :)
