### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by Silver-Snail** [racerretrocoder/Flightgear-F-22A-Raptor#32]
As I was going through a file, I saw that the autostart wasn't working, At the very top of the emu.nas file (/Nasal/emu.nas), I noticed these following lines of code:

    var engine1 = engines.Jet.new(0 , 0 , 0.01 , 5.21 , 4 , 4 , 0.05 , 1);
    var engine2 = engines.Jet.new(1 , 0 , 0.01 , 5.21 , 4 , 4 , 0.05 , 1);

    engine1.init();
    engine2.init();
A bit of debugging brought me to the conclusion that those might be the lines keeping it from working. So I removed them and autostart worked. I don't know what they're supposed to do, but autostart works without them.

**Comment by racerretrocoder** [comment]
Hmmmmmm i havent messed with that

**Comment by racerretrocoder** [comment]
its just been a thing from the first version

**Comment by racerretrocoder** [comment]
I was going to delete it anyways but it looks like you got it lol

**Comment by racerretrocoder** [comment]
Autostart is implanted fully now. 

See F22.nas for the code
