### ISSUE TITLE
My cockpit is not showing all of the gauges or the autopilot/radio controls

### ISSUE THREAD

**Issue by gambitim** [racerretrocoder/Flightgear-F-22A-Raptor#47]
I recently installed the f-22 and I noticed that the panel that should show the radio and autopilot controls is not.

This shows how some gauges are not working and the autopilot/radio panel is blank.
<img width="1136" alt="Screen Shot 2024-11-23 at 10 09 50 AM" src="https://github.com/user-attachments/assets/4451b18f-fcc3-4ee2-b08c-9641241804e2">

Compared to this photo which has both radio and autopilot controls.
![fgfs-20240815211814](https://github.com/user-attachments/assets/63c5dd96-4384-4043-80e9-4f3483ad7ff8)

I also noticed that the FCR doesn't seem to be working but that could just be operator error.

Please help if you can, I think that the problem is probably my fault but I would like to be able to use this plane as it was meant to be used.

**Comment by racerretrocoder** [comment]
I have big plans for this. i will make a nasal system to manage all the radios, autopilot and, navigation with all those buttons. its going to be a big chunk of coding. but itll be fun!

ill start working on this when i get home in a bit

theres also been this bug with the original cockpit where the text on the top buttons glitched out when i spawned in

**Comment by racerretrocoder** [comment]
![363424670-1777416a-0660-4340-8d45-a2fe02946fc7](https://github.com/user-attachments/assets/4332ce73-37cf-4a1e-8aaf-43b465b0b3d0)

**Comment by racerretrocoder** [comment]
But aft2r

**Comment by racerretrocoder** [comment]
dang it. on mobile. Sorry.

**Comment by racerretrocoder** [comment]
So that means ill have to make textures of all the buttons
(Maybe)

**Comment by racerretrocoder** [comment]
![image](https://github.com/user-attachments/assets/c315d12e-1ce2-42f7-9bd0-7fa03312f3e7)

**Comment by racerretrocoder** [comment]
I made them! :D

**Comment by racerretrocoder** [comment]
![image](https://github.com/user-attachments/assets/7ae70ceb-8920-44e1-8928-95ce5c3477b0)
How it works for the radios. you must enter a number using the keypad

**Comment by racerretrocoder** [comment]
![image](https://github.com/user-attachments/assets/b248d740-e0e7-4cab-b41e-1f306d0e55df)
Then press one of the "send" buttons

itll take that number and put it in the standby channel (the number far right) 
Then press the swap button to make the radio active.
